name: Meu primeiro Workflow de CI
on: 
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  exemplo:
    runs-on: ubuntu-latest
    steps:
      - name: Imprime mensagem de boas vindas
        run: "Iniciando meu primeiro job!"
      - name: Mostra diretório de trabalho
        run: pwd
      - name: Lista arquivos no runner
        run: ls -la