name: Meu Primeiro Workflow de CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  meu-primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - name: Exibe RA e Nome
        run: echo "6324558 - Luiz Felipe S. de Souza"
      - name: Mostra o diretório de trabalho
        run: pwd
      - name: Imprime nome do repositório
        run: echo "${{ github.repository }}"